### ISSUE TITLE
Use protobuf instead of JSON encoding

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-core#10]
**Description**
Need to implement protobuf encoding instead of JSON. 

**Tasks**
- [ ] Implement universe/encoding/protobuf.go in place of universe/encoding.go which implements JSON.
- [ ] Replace JSON with protobuf in http package
- [ ] Implement protobuf on Bluetooth side of things

When I implement stormdb/boltdb for core I'll add in tasks for using protobuf there as well.
