### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-core#2]
**Description**
These are the basic first steps to get started building this out.

**Tasks**
- [x] Establish domain-level constructs such as wallets, services, etc.
- [x] Mock a Bluetooth service
- [x] Wrap the Bluetooth service with an HTTP REST API

Once this is done I'll work on actually building the Bluetooth client, implementing real structs for the wallets, and more.
