### ISSUE TITLE
Week of 8/12 - Administrative Tasks

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-core#3]
**Description**
These are non-technical tasks to be done in order to keep the repo organized.

**Tasks**
- [x] Fix version tags;
- [x] Write the repo description;
- [x] Repo structure documentation.
- [x] nRF52840 issue with links to spec & cryptokit 

More will be added.

**Comment by itamarreif** [comment]
re: versioning https://github.com/universelabs/universe/issues/35#issue-480233415
