### ISSUE TITLE
Add Encryption facilities

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-core#7]
**Description**
Once a notion of login is established, encryption must be implemented 

**Tasks**
- [ ] Sketch encryption architecture;
- [ ] Decide on an encryption library to use;
- [ ] Implement in code.

Like #6, this is a very preliminary description of what needs to be done.
