### ISSUE TITLE
Sprint 6 - Critical Path

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-core#8]
**Description**
The following is a critical path list of all tasks needed to execute to meet the goals for the release of a functioning demo of Universe's Core software.

For Sprint 6 we have the goal to get a full alpha demo with the feather device working. The following tasks are required to do so.

Tasks

- [ ] #3 Week of 8/12 - Administrative Tasks
- [ ] #2 First steps
- [ ] #4 Basic Bluetooth Client
- [ ] #5 Blockstack Key Implementation
- [ ] #6 Login, Auth & Device Pairing
- [ ] #7 Encryption facilities

**Comment by guylepage3** [comment]
Nice @itamarreif.. I just assigned this issue a `Label` and to `Project` (kanban board).

**Comment by guylepage3** [comment]
Merged here.. https://github.com/universelabs/universe/issues/28
